### ISSUE TITLE
[BUG] [POSTGRES] AttributeError: 'type'

### ISSUE THREAD

**Issue by dwilliams782** [GoogleCloudPlatform/datacatalog-connectors-rdbms#48]
**What happened**:

I'm using the postgres connector to connect to a number of cloud SQL postgres databases, and I get the following result each time:

```
 docker run --net=host --rm --tty -v key:/data postgresql2datacatalog \
> --datacatalog-project-id=<> \
> --datacatalog-location-id=europe-west1 \
> --postgresql-host=localhost \
> --postgresql-port=5432 \
> --postgresql-user=<> \
> --postgresql-pass=<> \
> --postgresql-database=<> \
> --datacatalog-entry-group-id=postgres
INFO:root:
============Start postgres-to-datacatalog===========
INFO:root:

==============Scrape metadata===============
INFO:root:Scrapping basic metadata from connection_args
INFO:root:Scrapping additional metadata from connection_args,if configured
INFO:root:Refreshing metadata
INFO:root:Metadata analysis took 4.89955997467041 seconds to run.You can turn it off in ingest_cfg.yaml configuration file, using refresh_metadata_tables flag
INFO:root:Scraping metadata according to configuration file: ['sync_row_counts']
INFO:root:Executing query to process configuration option sync_row_counts
INFO:root:
1 table containers ready to be ingested...
INFO:root:

==============Prepare metadata===============
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/proto/message.py", line 555, in __getattr__
    pb_type = self._meta.fields[key].pb_type
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/google-datacatalog-postgresql-connector", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/postgresql/datacatalog_cli.py", line 102, in main
    PostgreSQL2DatacatalogCli().run(argv[1:] if len(argv) > 0 else argv)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/datacatalog_cli.py", line 55, in run
    user_config=self._get_user_config()).run()
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 93, in run
    tag_templates_dict = self.__create_tag_templates()
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 175, in __create_tag_templates
    tag_template_factory. \
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/prepare/datacatalog_tag_template_factory.py", line 61, in make_tag_template_for_table_container_metadata
    tag_template)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/prepare/datacatalog_tag_template_factory.py", line 165, in __add_creator_field_to_template
    '{} Creator'.format(attribute_type.capitalize()))
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/commons/prepare/base_tag_template_factory.py", line 40, in _add_primitive_type_field
    field.type.primitive_type = field_type
  File "/usr/local/lib/python3.7/site-packages/proto/message.py", line 560, in __getattr__
    raise AttributeError(str(ex))
AttributeError: 'type'

```

I have ran this against a dummy postgres container successfully but it fails against our cloud databases. 

**Anything else we need to know?**:

I'm fairly sure this is something in the set up of our databases and I am looking into it but any advice in the mean time would be excellent.

**Comment by mesmacosta** [comment]
Thanks @dwilliams782 for opening this, this was fixed on: https://github.com/GoogleCloudPlatform/datacatalog-connectors-hive/issues/20

Can you update your environment with the latest version of the connector?

**Comment by dwilliams782** [comment]
Hi mesmacosta, 

Thanks for the quick response. I was using the postgres-0.8.0 tag, but I've confirmed this does work OK with the latest master.

I may need to raise this as a separate feature request - we are indexing SQL databases in multiple projects, but ideally I would be able to confine the API calls (and this billing!) to one single project, which we can't do currently as the project-id you pass to the connector is used for the data catalog calls and the source of the data. It would be great to be able to pass in a source project and target project. Thoughts?

Thanks again.

**Comment by dwilliams782** [comment]
It would be ace to be able to override the resource URL as well, as this isn't reflective of where our database is.

**Comment by mesmacosta** [comment]
Hi @dwilliams782,

Can you open a feature request for it, describing the scenario? So we can keep the discussion there, WDYT?

Also can you elaborate with examples of what you mean by `source project `and `target project`?

The PostgreSQL instance can be in any GCP project or on-premise, and you can ingest them all in the same project, does it fit your use case? Or you would like to ingest them in different GCP projects?
