### ISSUE TITLE
[BUG] TypeError when ingesting MySQL 

### ISSUE THREAD

**Issue by supergreg77** [GoogleCloudPlatform/datacatalog-connectors-rdbms#73]
**What happened**:
Trying to ingest a local MySQL instance with a fresh schema and table.  Looks like database and table are scraped, but failing at the column level with a "TypeError: a bytes-like object is required, not 'str'" message:

```
==============Starting CLI===============
INFO:root:This SQL connector uses the default entry resoure URL
INFO:root:
============Start mysql-to-datacatalog===========
INFO:root:

==============Scrape metadata===============
INFO:root:Scrapping metadata from connection_args
DEBUG:mysql.connector.connection:# _do_auth(): user: root
DEBUG:mysql.connector.connection:# _do_auth(): self._auth_plugin: 
DEBUG:mysql.connector.connection:new_auth_plugin: caching_sha2_password
INFO:root:
1 table containers ready to be ingested...
INFO:root:

==============Prepare metadata===============
INFO:root:
--> database: Schema1
INFO:root:
1 tables ready to be ingested...
Traceback (most recent call last):
  File "/Users/gmartin/env/bin/google-datacatalog-mysql-connector", line 8, in <module>
    sys.exit(main())
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/mysql_/datacatalog_cli.py", line 101, in main
    MySQL2DatacatalogCli().run(argv[1:] if len(argv) > 0 else argv)
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/rdbms/datacatalog_cli.py", line 46, in run
    self._get_datacatalog_synchronizer()(
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 98, in run
    prepared_entries = self.__prepare_datacatalog_entries(
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 118, in __prepare_datacatalog_entries
    base_entries = base_entry_factory. \
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/rdbms/prepare/assembled_entry_factory.py", line 49, in make_entries
    assembled_tables = self.__make_entry_for_tables(
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/rdbms/prepare/assembled_entry_factory.py", line 77, in __make_entry_for_tables
    entry_id, entry = self.__datacatalog_entry_factory. \
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/rdbms/prepare/datacatalog_entry_factory.py", line 148, in make_entry_for_tables
    type=DataCatalogEntryFactory.__format_entry_column_type(
  File "/Users/gmartin/env/lib/python3.8/site-packages/google/datacatalog_connectors/rdbms/prepare/datacatalog_entry_factory.py", line 173, in __format_entry_column_type
    formatted_name = source_name.replace('&', '_')
TypeError: a bytes-like object is required, not 'str'

```

**Anything else we need to know?**:
I'm not sure if it makes a difference, but I've tried this with both empty and populated tables with the same results

**Comment by mesmacosta** [comment]
@supergreg77 I will publish a version of the connector this week with the change.
