### ISSUE TITLE
[BUG] status = StatusCode.UNIMPLEMENTED

### ISSUE THREAD

**Issue by papezt** [GoogleCloudPlatform/datacatalog-connectors-rdbms#76]
**What happened**:
Docker entrypoint for Postgresql is not working and throwing errors:

`==============Ingest metadata===============
DEBUG:google.auth._default:Checking /data/postgresql2dc-credentials.json for explicit credentials as part of auth process...
INFO:root:
INFO:root:Starting to clean up the catalog...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
INFO:root:0 entries that match the search query exist in Data Catalog!
INFO:root:Looking for entries to be deleted...
INFO:root:0 entries will be deleted.
INFO:root:
Starting to ingest custom metadata...
DEBUG:google.auth._default:Checking /data/postgresql2dc-credentials.json for explicit credentials as part of auth process...
INFO:root:
INFO:root:Starting the ingestion flow...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Received http2 header with status: 404"
        debug_error_string = "{"created":"@1635945945.865156300","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":133,"grpc_message":"Received http2 header with status: 404","grpc_status":12,"value":"404"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/google-datacatalog-postgresql-connector", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/postgresql/datacatalog_cli.py", line 105, in main
    PostgreSQL2DatacatalogCli().run(argv[1:] if len(argv) > 0 else argv)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/datacatalog_cli.py", line 58, in run
    config=self._get_config()).run()
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 107, in run
    self.__ingest_metadata(prepared_entries, tag_templates_dict)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 171, in __ingest_metadata
    tag_templates_dict)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 185, in __ingest_base_entries_metadata
    tag_templates_dict)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/commons/ingest/datacatalog_metadata_ingestor.py", line 51, in ingest_metadata
    self.__create_tag_templates(tag_templates_dict)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/commons/ingest/datacatalog_metadata_ingestor.py", line 76, in __create_tag_templates
    tag_template=tag_template)
  File "/usr/local/lib/python3.7/site-packages/google/datacatalog_connectors/commons/datacatalog_facade.py", line 278, in create_tag_template
    tag_template=tag_template)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/datacatalog_v1beta1/services/data_catalog/client.py", line 1508, in create_tag_template
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 Received http2 header with status: 404`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Version: 0.7.1
Docker entry point is copy-paste from documentation

**Anything else we need to know?**:

Thank you for helping

**Comment by mesmacosta** [comment]
@papezt this seems to be an issue similar to https://github.com/GoogleCloudPlatform/datacatalog-connectors-hive/issues/18

Can you look at comments from that issue? to sum up, verify what you are using in the `...DATACATALOG_LOCATION_ID`, if it's a valid `location_id`.

Let me know if that works for you.

**Comment by papezt** [comment]
Oh my! Thank you, I'm just blind.
